// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Current platform
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVMI6KrfHTy7QHKbogWKyPD0oCu_QYYI',
    appId: '1:1055467771631:android:0574f77952fc69d317ad1a',
    messagingSenderId: '1055467771631',
    projectId: 'kura-777b6',
    storageBucket: 'kura-777b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTDeJ9_oGkR68-qHyVgycuDinJjB_jtQ',
    appId: '1:1055467771631:ios:ebc5c129978af09f17ad1a',
    messagingSenderId: '1055467771631',
    projectId: 'kura-777b6',
    storageBucket: 'kura-777b6.appspot.com',
    androidClientId: '1055467771631-2fda7sj2snr7f6j4uotrdqjikq1nj5ms.apps.googleusercontent.com',
    iosClientId: '1055467771631-1hbeiqv3r2u54lqkpii6e5r5fpl144ph.apps.googleusercontent.com',
    iosBundleId: 'com.app.tClient',
  );
}
